default_platform(:ios)

platform :ios do
  desc "Sync certificates and provisioning profiles"
  lane :certificates do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: is_ci
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: is_ci
    )

    app_id = ENV["APP_BUNDLE_ID"]

    current_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: app_id
    )
    increment_build_number(
      build_number: current_build + 1,
      xcodeproj: "PandaBeFree.xcodeproj"
    )

    build_app(
      project: "PandaBeFree.xcodeproj",
      scheme: "PandaBeFree",
      clean: true,
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          app_id => "match AppStore #{app_id}",
          "#{app_id}.widgets" => "match AppStore #{app_id}.widgets"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
